const { MessageEmbed } = require('discord.js');

module.exports = {
    name: "quote",
    aliases: ["Quote"],
    description: "Get a random quote.",
    category: "fun",
    cooldown: 5,
    premium: false,

    run: async (client, message, args) => {
        try {
            const quotes = [
                "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
                "The purpose of our lives is to be happy. - Dalai Lama",
                "Life is what happens when you're busy making other plans. - John Lennon",
                "Get busy living or get busy dying. - Stephen King",
                "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
                "Believe you can and you're halfway there. - Theodore Roosevelt",
                "The best way to predict the future is to create it. - Peter Drucker",
                "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
                "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
                "The power of imagination makes us infinite. - John Muir",
                "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
                "Do what you can, with what you have, where you are. - Theodore Roosevelt",
                "Dream big and dare to fail. - Norman Vaughan",
                "You miss 100% of the shots you don't take. - Wayne Gretzky",
                "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
                "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
                "The most important thing is to try and inspire people so that they can begreat in whatever they want to do. - Kobe Bryant",
                "The harder I work, the luckier I get. - Gary Player",
                "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
                "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
                "Strive not to be a success, but rather to be of value. - Albert Einstein",
                "The best way out is always through. - Robert Frost",
                "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
                "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
                "The best way to predict the future is to create it. - Peter Drucker",
                "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
                "The way to get started is to quit talking and begin doing. - Walt Disney",
                "The person who says it cannot be done should not interrupt the person who is doing it. - Chinese Proverb",
                "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
                "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. - Winston Churchill",
                "The only true wisdom is in knowing you know nothing. - Socrates",
                "The greatest weapon against stress is our ability to choose one thought over another. - William James",
                "The best thing about the future is that it comes one day at a time. - Abraham Lincoln",
                "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
                "The best way to get started is to quit talking and begin doing. - Walt Disney",
                "The biggest risk is not taking any risk. - Mark Zuckerberg",
                "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
                "The best way to predict your future is to create it. - Abraham Lincoln",
                "The only thing to fear is fear itself. - Franklin D. Roosevelt",
                "The best way to not feel hopeless is to get up and do something. Don’t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope. - Barack Obama",
                "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
                "The best revenge is massive success. - Frank Sinatra",
            ];

            const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];

            const embed = new MessageEmbed()
                .setTitle("Quote")
                .setDescription(randomQuote)
                .setColor(client.color);

            message.channel.send({ embeds: [embed] });
        } catch (err) {
            console.error(err);
            message.channel.send("An error occurred while fetching the quote. Please try again later.");
        }
    }
};
